version: '3'
services:
  web:
    image: testtdockertest/docker-demo:v1
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "18080:8080"
    networks:
      - webnet
networks:
  webnet:
