name:
  value: test

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  zipkin:
    base-url: http://192.168.7.46:9411
  sleuth:
    sampler:
      probability: 1

management:
  endpoints:
    web:
      exposure:
        include: "*"

logstash:
  host: 192.168.7.46
  port: 5000
  queue-size: 512