server:
  port: 8992

spring:
  jpa:
    #启用SQL语句的日志记录
    show-sql: true
  datasource:
    #数据库连接设置
    url: jdbc:h2:mem:dbtest;database_to_upper=false
    username: sa
    password: sa
    driverClassName: org.h2.Driver
    #表明使用的数据库平台是h2
    platform: h2
    #进行该配置后，每次启动程序，程序都会运行resources/db/schema.sql文件，对数据库的结构进行操作
    #schema: classpath:db/schema.sql
    #进行该配置后，每次启动程序，程序都会运行resources/db/data.sql文件，对数据库的数据操作
    #data: classpath:data.sql
  h2:
    console:
      enabled: true
      #进行该配置，你就可以通过URL/h2访问h2 web consloe
      path: /h2
      #配置为true，h2 web consloe就可以在远程访问了，否则只能在本机访问
      settings:
        web-allow-others: false
